# This workflow will build a golang project

name: ci-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: simple_bank
        ports:
          - 5433:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download and extract migrate
        run: curl -sL https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz

      # Langkah 2: Pindahkan file hasil ekstraksi ke /usr/bin
      - name: Move migrate binary to /usr/bin
        run: sudo mv migrate.linux-amd64 /usr/bin/migrate

      # Langkah 3: Verifikasi instalasi
      - name: Verify migrate installation
        run: which migrate

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
